#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

// Simple dist builder: resolves local @import url(...) statements
// and concatenates referenced files in order. Does not fetch remote URLs.

const repoRoot = path.resolve(__dirname, '..');
const cssRoot = path.join(repoRoot, 'css');
const entry = path.join(cssRoot, 'final-fantasy.css');
const outDir = path.join(repoRoot, 'dist');
const outFile = path.join(outDir, 'final-fantasy.css');

function readFileSafe(p){
  if(!fs.existsSync(p)) return null;
  return fs.readFileSync(p,'utf8');
}

function resolveImportPath(baseDir, importPath){
  // strip surrounding url(...) or quotes
  importPath = importPath.trim();
  importPath = importPath.replace(/^url\((.*)\)$/,'$1').replace(/^['"]|['"]$/g,'');
  // ignore absolute URLs (http/https)
  if(/^https?:\/\//.test(importPath)) return null;
  // if path is relative, resolve
  return path.resolve(baseDir, importPath);
}

function processCss(filePath, seen){
  seen = seen || new Set();
  if(!filePath || seen.has(filePath)) return '';
  seen.add(filePath);
  const content = readFileSafe(filePath);
  if(content === null) {
    console.warn('Missing file:', filePath);
    return '';
  }

  const dir = path.dirname(filePath);
  let out = `/* ===== ${path.relative(repoRoot, filePath)} ===== */\n`;
  // Process @import url(...) and @import "..." occurrences
  const importRegex = /@import\s+(?:url\()?\s*([^)';]+|"[^"]+"|'[^']+')\s*\)?\s*;?/g;
  let lastIndex = 0;
  let m;
  while((m = importRegex.exec(content)) !== null){
    const matchStart = m.index;
    // append content before this import
    out += content.slice(lastIndex, matchStart);
    lastIndex = importRegex.lastIndex;
    const rawPath = m[1];
    const resolved = resolveImportPath(dir, rawPath);
    if(resolved){
      // If the resolved path is a directory or not a .css, try adding .css
      let candidate = resolved;
      if(!path.extname(candidate)) candidate = candidate + '.css';
      if(!fs.existsSync(candidate) && fs.existsSync(resolved + '.css')) candidate = resolved + '.css';
      if(fs.existsSync(candidate)){
        out += processCss(candidate, seen);
        continue; // skip adding the import line itself
      } else {
        // not found, skip but keep the import as-is
        out += `/* skipped unresolved import: ${rawPath} */\n`;
      }
    } else {
      // remote import (http), keep as-is
      out += m[0] + '\n';
    }
  }
  // append remaining content
  out += content.slice(lastIndex);
  return out + '\n';
}

function ensureDir(d){ if(!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); }

function build(){
  ensureDir(outDir);
  const result = processCss(entry);
  // simple header
  const header = `/* Final Fantasy CSS - built dist (generated by scripts/build-dist.js) */\n`;
  fs.writeFileSync(outFile, header + '\n' + result, 'utf8');
  console.log('Wrote', outFile);
}

build();
